### ISSUE TITLE
[Q] How to hide an absolute path?

### ISSUE THREAD

**Issue by xplshn** [MikeHorn-git/Kernel-Dev#1]
Hi, great project. I'm using it as reference to implement basically the same, at https://github.com/xplshn/hidefs, I'm trying to wrap my head around how to hide a specific absolute path, not just things with a certain prefix or name, any thoughts on this?

Help is greatly appreciated! Thanks!

**Comment by MikeHorn-git** [comment]
Hello, thanks for your message.

I don't have any idea sorry.

**Comment by xplshn** [comment]
I forgot to close the issue, I think using the inode is enough, which should be stored in regs->r8.


Thanks anyways
